### ISSUE TITLE
Input Range

### ISSUE THREAD

**Issue by dbltv** [quqixun/CTReconstruction#2]
In the file filtered_back_projection.m in which range should input be?
I have the following error:
Index exceeds matrix dimensions.

Error in filtered_back_projection (line 93)
    img_fbp = img_fbp + interp1(1:gl, gffi(:, t), pos);

**Comment by quqixun** [comment]
I did not get your point.

The only needed input is the sinogram.
https://github.com/quqixun/CTReconstruction/blob/master/BackProjection/CT_reconstruction.m#L49

The data I used can be found here.
https://github.com/quqixun/MyChalmerse/tree/master/SSY186%20-%20Diagnostic%20Imaging/CTProject/code

They are data.nat and data2.mat.
